### ISSUE TITLE
版本1.3.1编译后报错，显示frontend\server.go:26:12: pattern dist: no matching files found

### ISSUE THREAD

**Issue by buyanla** [nopdan/rose#10]
![image](https://github.com/nopdan/rose/assets/77561058/03fd3363-965d-40c3-8abc-2b081f19e27b)
用powershell打开后，进行如上编译，结果如下：
Submodule path 'UnicodeCJK-WuBi': checked out '7f55c865a6acfdb1d298d90c42650748f358a3cf'
Submodule path 'pinyin-data': checked out 'f1d68ebf07c1781e0c6b923ddaccab4d1d6eb421'
缂栬瘧 windows 鐗堟湰
**frontend\server.go:26:12: pattern dist: no matching files found**

**Comment by nopdan** [comment]
脚本里没有写编译前端的命令，可以手动进入 frontend 文件夹执行 pnpm build。

**Comment by buyanla** [comment]
好啦好啦，谢谢nopdan！
