### ISSUE TITLE
搜狗拼音词库.bin 转换为 微软拼音自学习词汇.dat 后，导入失败（文件格式错误或文件已损坏）

### ISSUE THREAD

**Issue by YangShaoyue** [nopdan/rose#11]
平台：Windows 11

问题描述：
1. 搜狗拼音输入法导出词库
![image](https://github.com/nopdan/rose/assets/12428824/000ef444-9ba2-44b9-bd90-d7f0594e01a0)
2. 使用本工具导出 微软拼音自学习词汇.dat
![image](https://github.com/nopdan/rose/assets/12428824/62850eb3-7ab4-405c-812b-175e489cae3a)
3. 导入 微软拼音自学习词汇.dat 后报错：
![image](https://github.com/nopdan/rose/assets/12428824/af2cbd03-46f6-474d-840e-f9e5acfa57bf)

PS：我使用深蓝词库转换工具 v3.1 也是同样的报错

**Comment by nopdan** [comment]
无法复现

**Comment by YangShaoyue** [comment]
> 无法复现

刚发现使用本工具后，终端有几行类似报警的日志：
![image](https://github.com/nopdan/rose/assets/12428824/dafc7324-6add-42ef-8033-a38e32e84a00)
请问导入失败与此有关吗？

另外，有办法查看 win11 微软拼音自学习词汇导入日志吗？能查看的话，我也可以提供

**Comment by nopdan** [comment]
长词是跳过了的。初步怀疑是搜狗词库拼音编码中有微软不支持的编码，可以的话提供你的搜狗备份文件，mailto:xci@live.com

**Comment by YangShaoyue** [comment]
> 长词是跳过了的。初步怀疑是搜狗词库拼音编码中有微软不支持的编码，可以的话提供你的搜狗备份文件，[mailto:xci@live.com](mailto:xci@live.com)

感谢，搜狗词库已经通过邮箱发送给你。

**Comment by nopdan** [comment]
修复了，https://github.com/nopdan/rose/actions/runs/9029378170 可以下载。
重构拖了很久暂时不准备发版

**Comment by YangShaoyue** [comment]
> 修复了，https://github.com/nopdan/rose/actions/runs/9029378170 可以下载。 重构拖了很久暂时不准备发版

非常感谢，已经导入成功

**Comment by aodianjun** [comment]
你发错人了




有失败就有成功
***@***.***
