### ISSUE TITLE
搜狗细胞词库转谷歌拼音词库无法正常使用

### ISSUE THREAD

**Issue by fengguowudi** [nopdan/rose#5]
Gboard个人词典导入后
字词一栏显示为1
快捷键为设置字词
拼音并未录入

理想状态
字词一栏填充入字词
拼音填充入快捷键栏

[开发大神专用词库【官方推荐】.scel_谷歌拼音.txt](https://github.com/nopdan/rose/files/13691447/scel_.txt)
转换后的文件

**Comment by nopdan** [comment]
谷歌拼音和 Gboard 不是一个东西
